import {useRouter} from "next/router";
import BlogArticleComponent from "@/components/article_page/blog_article_component";
import Loading from "@/pages/loading";
import Head from "next/head";
import React, {useEffect, useState} from "react";
import {fetchArticles} from "@/lib/prisma";
import useSWR from "swr";

export async function getStaticProps(staticProps) {
    const params = staticProps.params;
    const intendedArticleId = parseInt(params.article_id)

    const articles = await fetchArticles();
    const article = articles.find((item) => {
        // be aware that item.id is number where params.article_id is string
        return item.id === intendedArticleId // dynamic page id
    });

    if (article === undefined) {
        console.log("article is undefined ...")
        return {
            notFound: true, //redirects to 404 page
        };
    }

    const featuredArticles = articles.filter((item) => {
        let n = (Math.abs(item.id - intendedArticleId) % articles.length)
        return n >= 1 && n <= 3;
    })

    return {
        props: {
            intendedArticle: article,
            featuredArticles: featuredArticles,
        }
    }
}

export async function getStaticPaths() {

    const articles = await fetchArticles();

    return {
        paths: articles.map((item) => {
            return {params: {article_id: `${item.article_id}`}}
        }),
        fallback: true
    }
}

const ArticleComponent = ({intendedArticle, featuredArticles}) => {

    const fetcher = (url) => fetch(url).then((res) => res.json());
    const [likesCount, setLikesCount] = useState(intendedArticle.nLikes);
    const { data, error } = useSWR(`http://localhost:3030/api/getArticleLikesCountById?id=${intendedArticle.id}`, fetcher);
    useEffect(() => {
        if (error) {
            throw new Error("Something went wrong.")
        }

        if (data) {
            setLikesCount(data.nLikes);
        } else {
            setLikesCount(0);
        }
    }, [data]);

    const [doesCurrentUserLike, setDoesCurrentUserLike] = useState(false);

    const router = useRouter();

    if (router.isFallback) {
        return <Loading/>
    }





    return (
        // <>
        //     <Head>
        //         <title>{article.title}</title>
        //     </Head>
        //     <h1>
        //         Article with id: {router.query.article_id}
        //     </h1>
        //     <h2>
        //         Article Title: {article.title}
        //     </h2>
        //     {Object.values(data).map((item) => {
        //         return <div key={item.title}>
        //             <h1>{item.title}</h1>
        //             <p>{item.body}</p>
        //         </div>
        //     })
        //     }
        // </>
        <>
            <Head>
                <title>{intendedArticle.title}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <BlogArticleComponent
                intendedArticle={intendedArticle}
                featuredArticles={featuredArticles}
                likesCount={likesCount}
                setLikesCount={setLikesCount}
                doesCurrentUserLike={doesCurrentUserLike}
                setDoesCurrentUserLike={setDoesCurrentUserLike}
            />
        </>
    )
}

export default ArticleComponent;