// 404.js

import {AnimatedHomeIcon} from "../components/AnimatedIcons";
import * as React from 'react';
import {useContext} from 'react';
import {
    alpha,
    Box,
    CircularProgress,
    Grid,
    ListItem,
    ListItemButton,
    ListItemIcon,
    ListItemText,
    Typography
} from "@mui/material";
import {useTheme} from '@mui/material/styles';
import Head from "next/head";
import Link from "next/link";

import {SkeletonContext} from "./_app"

export default function Loading(props) {
    const {state, dispatch} = useContext(SkeletonContext);


    const theme = useTheme();

    return (
        <>
            <Head>
                <title>Loading ...</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>


            <Box
                style={{
                    position: "fixed",
                    top: "50%",
                    left: "50%",

                    /* bring your own prefixes */
                    transform: "translate(-50%, -50%)",
                }}

                sx={{
                    width: {
                        xs: "95%",
                        sm: "65%",
                        md: "55%",
                        lg: "50%"
                    },
                }}
            >


                <Grid
                    container={"true"}

                    height={1}
                >
                    <Grid
                        item
                        padding={2}
                        margin={1}

                        sx={{
                            display: "flex",
                            flexDirection: "column",
                        }}
                        xs={12}
                        sm={12}
                        md={12}
                        lg={12}
                        style={{
                            background: alpha(theme.palette.background.default, 0.35),
                            backdropFilter: "blur(10.5px)",
                            borderWidth: 50,
                            border: "solid",
                            borderColor: alpha(theme.palette.background.paper, 0.2),
                        }}
                    >
                        <ListItem
                            style={{
                                backgroundColor: theme.palette.primary.main,
                                height: "12vh",
                                flexGrow: 1,
                                alignItems: "center",
                                alignSelf: "center",
                                alignContent: "center",
                            }}
                        >
                            <ListItemIcon>
                                <CircularProgress color="inherit"/>
                            </ListItemIcon>
                            <ListItemText>
                                <Typography color={theme.palette.text.primary} variant={"h5"} component={"h1"}>
                                    Loading ...
                                </Typography>
                            </ListItemText>
                        </ListItem>

                        <Box>

                        </Box>

                        <Link
                            legacyBehavior
                            href={"/home"}
                        >
                            <a>
                                <ListItemButton
                                    sx={{height: "12vh"}}
                                    key={"backtohome"}
                                >
                                    <ListItemIcon><AnimatedHomeIcon/></ListItemIcon>
                                    <ListItemText padding={10} primary={
                                        <Typography
                                            color={theme.palette.text.primary}
                                            variant={"body1"}
                                        >
                                            Back To Home
                                        </Typography>}
                                    />
                                </ListItemButton>
                            </a>
                        </Link>
                    </Grid>
                </Grid>
            </Box>
        </>
    )
}